# Makefile

LUA_VERSION = 5.1
LUA_INCLUDE = /opt/homebrew/Cellar/lua/5.1.5_8/include/lua-5.1
LUA_LIBDIR = /opt/homebrew/Cellar/lua/5.1.5_8/lib

CFLAGS = -Wall -Wextra -fPIC -I$(LUA_INCLUDE)
LDFLAGS = -shared -L$(LUA_LIBDIR) -llua$(LUA_VERSION)

all: time.so

time.so: time.c
	gcc $(CFLAGS) $< -o $@ $(LDFLAGS)

clean:
	rm -f time.so
